### PR TITLE
Build script

### PR DESCRIPTION
**Pull request by oliverdain**
I wrote a script that automatically builds all the images in dependency order, auto-updates the version numbers of the dependencies in the `FROM` lines of the `Dockerfiles`, etc. I ported the `base` and `python` images to use it. Wanted to get some feedback before next steps. If y'all like it the next step would be to update this PR so that all our base images use this new tool and then update our CircleCI build so it just calls the script instead of explicitly listing each container and container version we want CircleCI to build. It seems like this maybe makes everything a lot more maintainable.

Depends on #7 

First new commit: 0ca4958c57b75ece9666c4f153985ff689b8e340

### CODE REVIEW

**Comment by colindavey** [comment]
I wonder if a no_build parameter would be useful, so it would be possible to give it a run that just shows you what would be built and pushed.

**Comment by colindavey** [comment]
Thinking out loud if the default should be push or no_push.

**Comment by colindavey** [comment]
Should the file be checked in with chmod as executable? I made it executable, and now git status shows the file as modified.

**Comment by colindavey** [comment]
Locally, I added a `python_w_vim` container that depends on python -- not because I wanted this, but to test with a grandparent dependency. I think I found a bug. 

The generated Dockerfile for `python_w_vim` has
```FROM mvpstudio/python:v002```
but it should be
```FROM mvpstudio/python:v004```
because python is up to version 4. 
And I think the problem is around [here](
https://github.com/MVPStudio/docker-images/blob/4ea6a8e689f60a7ccad3aca46dc049a44e0fcd79/build-push.py#L91-L93) because a print of `template_data` shows `{'base': 'v002', 'python': 'v004'}` and it's picking up the version number of `base` instead of `python`. 

Alternatively, pass in just the parent dependency instead of the complete built list into build_one. 

Alternatively use the item's own deps list to lookup up the version number of its dependency.

**Comment by colindavey** [comment]
Consider generating the build-folder in one step, the builds in another, and the pushes in a 3rd. Then you have the option of inspecting the results for each step before going on to the next. The first step would preserve the order in which to build things.

**Comment by colindavey** [comment]
Are `deps` just for base images that go in the `FROM` line? Can there be more than one? If there can only be one base image, but there might be other types of dependencies, maybe have separate dependency item (e.g. `image_dep` and `deps`).

**Comment by oliverdain** [comment]
Just updated this. Changes:

1. Should work with CircleCI (testing in a moment)
2. No longer needs the .yml file - can infer evertying from directory names and the `Dockerfile.template`
3. Now pulls version numbers from Dockerhub API so you don't specify them and you don't have to worry about forgetting to update them.

Going to test with CircleCI and then update the remaining container builds to be in this format at which point I'll push one final commit and this should be ready to merge (pending approval from @slively  and/or @codegold79 ).

**Comment by oliverdain** [comment]
> I wonder if a no_build parameter would be useful, so it would be possible to give it a run that just shows you what would be built...

I don't object. Generally I try to keep PRs small and we can then add to them. This one is already pretty big. Personally I don't see a ton of value in the `--no_build` but feel free to send a PR with that change if you see it being useful.

> Thinking out loud if the default should be push or no_push.

The plan is that individuals pretty much never run this directly - you rely on the CI to run it. As such it seems OK to have push be the default but I can certainly change if others disagree.

> And I think the problem is around here because a print of template_data shows {'base': 'v002', 'python': 'v004'} and it's picking up the version number of base instead of python.

I'm guessing that's 'cause your `Dockerfile.template` contained `{{ base }}` rather than `{{ python }}`?

> Consider generating the build-folder in one step, the builds in another, and the pushes in a 3rd. Then you have the option of inspecting the results for each step before going on to the next. The first step would preserve the order in which to build things.

If you want to inspect the `build` directory you could pass your theoretical `--no_build` parameter and `--no_build` would imply `--no_push` so I think that'd have the same effect. Then running with `--no_push` would let you inspect the built images. Since building locally isn't generally a problem I think most people who wanted to make sure their new image would build would just run with `--no_push` and `--only` and then you can see if your image builds and, if desired, inspect the `build` directory. I think that ends up having pretty much the same effect with less effort for the user.

> Are deps just for base images that go in the FROM line? Can there be more than one? If there can only be one base image, but there might be other types of dependencies, maybe have separate dependency item (e.g. image_dep and deps).

Correct. In fact, you no longer need the `container.yml` and we infer your dependencies by reading your `Dockerfile.template` and seeing which Mustache varaibles it requires.

Yes, there can be more than one dependency if multi-stage builds are used. I don't think there's multiple _kinds_ of dependencies, but if there are I'm not sure what is gained by separating them out; the code would then just have to immediately concatenate them and would ignore the types from then on.

**Comment by colindavey** [comment]
> > I wonder if a no_build parameter would be useful, so it would be possible to give it a run that just shows you what would be built...
> 
> I don't object. Generally I try to keep PRs small and we can then add to them. This one is already pretty big. Personally I don't see a ton of value in the `--no_build` but feel free to send a PR with that change if you see it being useful.

The use would be to at least to save time while testing the script itself. For example to quickly eyeball the generated Dockerfiles without having to wait for the builds. 

> > And I think the problem is around here because a print of template_data shows {'base': 'v002', 'python': 'v004'} and it's picking up the version number of base instead of python.
> 
> I'm guessing that's 'cause your `Dockerfile.template` contained `{{ base }}` rather than `{{ python }}`?

Note that the generated Docker file had 
`FROM mvpstudio/python:v002`
not
`FROM mvpstudio/base:v002`

> Correct. In fact, you no longer need the `container.yml` and we infer your dependencies by reading your `Dockerfile.template` and seeing which Mustache varaibles it requires.

Actually right before I saw your new changes, I was thinking "wait a minute, everything in the yaml could be easily derived."

**Comment by colindavey** [comment]
> > And I think the problem is around here because a print of template_data shows {'base': 'v002', 'python': 'v004'} and it's picking up the version number of base instead of python.
> 
> I'm guessing that's 'cause your `Dockerfile.template` contained `{{ base }}` rather than `{{ python }}`?

Sorry, I misspoke above! You are correct!

**Comment by oliverdain** [comment]
@slively and @codegold79 OK, all exiting container builds ported over to this new format. I wasn't able to test the circleci build - I don't see any way to manually trigger a build. I suppose if you approve and merge we'll see if the build works.

**Comment by oliverdain** [comment]
@slively any thoughts here?

**Comment by slively** [comment]
It's beautiful and I'm super late.

**Pull request merged**
